### ISSUE TITLE
ImportError: cannot import name 'ITokenChecker' from 'pylint.interfaces'  with pylint 3

### ISSUE THREAD

**Issue by tbutler-qontigo** [mxmeinhold/pylint-fixme-info#3]
Hi

Using this plugin with pylint `3.2.5`, I get `ImportError: cannot import name 'ITokenChecker' from 'pylint.interfaces' ` in every case I tried

Python `3.10.14` in github actions:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pylint/lint/run.py", line 155, in __init__
    linter.load_plugin_modules(self._plugins)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 379, in load_plugin_modules
    module = astroid.modutils.load_module_from_name(modname)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/astroid/modutils.py", line 196, in load_module_from_name
    module = importlib.import_module(dotted_name)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 2[41](https://github.com/Qontigo/Research-WealthLens/actions/runs/9756356729/job/26926508182#step:10:42), in _call_with_frames_removed
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pylint_fixme_info/__init__.py", line 7, in <module>
    from pylint.interfaces import ITokenChecker
ImportError: cannot import name 'ITokenChecker' from 'pylint.interfaces' (/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pylint/interfaces.py)
```

Windows 11 with python `3.11.9`:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pylint\__main__.py", line 10, in <module>
    pylint.run_pylint()
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pylint\__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pylint\lint\run.py", line 155, in __init__
    linter.load_plugin_modules(self._plugins)
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pylint\lint\pylinter.py", line 379, in load_plugin_modules
    module = astroid.modutils.load_module_from_name(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\astroid\modutils.py", line 196, in load_module_from_name
    module = importlib.import_module(dotted_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pylint_fixme_info\__init__.py", line 7, in <module>
    from pylint.interfaces import ITokenChecker
ImportError: cannot import name 'ITokenChecker' from 'pylint.interfaces' (C:\Users\XXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pylint\interfaces.py)
```
and WSL2 using python `3.10.12`
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/XXX/.local/lib/python3.10/site-packages/pylint/__main__.py", line 10, in <module>
    pylint.run_pylint()
  File "/home/XXX/.local/lib/python3.10/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/home/XXX/.local/lib/python3.10/site-packages/pylint/lint/run.py", line 162, in __init__
    args = _config_initialization(
  File "/home/XXX/.local/lib/python3.10/site-packages/pylint/config/config_initialization.py", line 61, in _config_initialization
    linter.load_plugin_modules(utils._splitstrip(config_data["load-plugins"]))
  File "/home/XXX/.local/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 379, in load_plugin_modules
    module = astroid.modutils.load_module_from_name(modname)
  File "/home/XXX/.local/lib/python3.10/site-packages/astroid/modutils.py", line 196, in load_module_from_name
    module = importlib.import_module(dotted_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/XXX/.local/lib/python3.10/site-packages/pylint_fixme_info/__init__.py", line 7, in <module>
    from pylint.interfaces import ITokenChecker
ImportError: cannot import name 'ITokenChecker' from 'pylint.interfaces' 
```
Is there a workaround/fix?
Thanks

**Comment by mxmeinhold** [comment]
It's been a while since I needed this module, so I haven't been actively maintaining it

Looks like this was deprecated in 2.14, and removed in 3.0: https://github.com/pylint-dev/pylint/commit/000c6f8985ce6b6d9c7e45e63d7a65b4eda24897

I believe it can be replaced with the [`BaseTokenChecker`](https://github.com/pylint-dev/pylint/blob/d281f2fbf9672706ac07ee45d7cff3c4e2ff83bb/pylint/checkers/base_checker.py#L230) in the current version of pylint, as it has the same signature, though from my initial test, it seems a few other things have changed and it isn't a simple drop in replacement. If you happen to dig further, I'm happy to accept PRs, but I won't be able to do a release or attempt a fix myself until late today or tomorrow, so the published package won't be updated before then

**Comment by mxmeinhold** [comment]
I did actually get what I believe is a working version, on [the pylint-3 branch](https://github.com/mxmeinhold/pylint-fixme-info/tree/pylint-3), but still need to validate and properly publish it

**Comment by tbutler-qontigo** [comment]
Great, thanks for looking at it so quickly.
I'm afraid I'm not really a python programmer - I am coming from a devops angle, building piplines to build and test apps and run code quality analyses over the code....

**Comment by mxmeinhold** [comment]
No worries! If you want to try the patch, you can directly install the package from the branch ([pip docs](https://pip.pypa.io/en/stable/topics/vcs-support/)), otherwise I hope to have a release for you by midday tommorrow

**Comment by tbutler-qontigo** [comment]
just tried it and it does indeed seem to work.  Tomorrow would be great!
thanks

**Comment by mxmeinhold** [comment]
1.0.4 is out, supporting pylint>=2.14.0

**Comment by tbutler-qontigo** [comment]
Awesome, thanks for the amazingly rapid response!
